clinic/urls.py
from django.conf.urls import url
from . import views

app_name = 'clinic'


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<appointment_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<consultation_id>[0-9]+)/isdoctor/$',
        views.isdoctor, name='isdoctor'),
    url(r'^consultation/(?P<filter_by>[a-zA-Z]+)/$',
        views.consultations, name='consultations'),
    url(r'^create_appointment/$', views.create_appoinment,
        name='create_appointment'),
    url(r'^(?P<appointment_id>[0-9]+)/create_consultation/$',
        views.create_consultation, name='create_consultation'),
    url(r'^(?P<appointment_id>[0-9]+)/delete_consultation/(?P<appointment_id>[0-9]+)/$',
        views.delete_consultation, name='delete_consultation'),
    url(r'^(?P<appointment_id>[0-9]+)/favourite_appointment/$',
        views.favourite_appointment, name='favourite_appointment'),
    url(r'^(?P<appointment_id>[0-9]+)/delete_appointment/$',
        views.delete_appointment, name='delete_appointment'),
]

doctorClinic/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^appointment/', include('clinic.urls')),
    url(r'', include('clinic.urls')),
]

clinic/models.py
from datetime import time
from django.db import models
from django.contrib.auth.models import Permission, User

# Create your models here.


class Appoinment(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    date = models.CharField(max_length=20)
    patient_name = models.CharField(max_length=250)
    doctor = models.CharField(max_length=250)
    time = models.CharField(max_length=250)
    file_number = models.CharField(max_length=20)
    is_doctor = models.BooleanField(default=False)

    def __str__(self):
        return self.doctor + '-' + self.patient_name


class Consultation(models.Model):
    appoinment = models.ForeignKey(Appoinment, on_delete=models.CASCADE)
    consultation_number = models.CharField(max_length=250)
    doctor_name = models.CharField(max_length=250)
    patient_name = models.CharField(max_length=250)
    file_number = models.CharField(max_length=20)
    is_doctor = models.BooleanField(default=False)

    def __str__(self):
        return self.doctor_name + '-' + self.patient_name

clinic/forms.py
from django.contrib.auth.models import User
from django import forms
from django.db import models
from django.forms import fields
from .models import Appoinment, Consultation


class UserForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput)
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class AppoinmentForm(forms.ModelForm):
    class Meta:
        model = Appoinment
        fields = ['date', 'patient_name', 'doctor',
                  'time', 'file_number', 'is_doctor']


class ConsultationForm(forms.ModelForm):
    class Meta:
        model = Consultation
        fields = ['consultation_number', 'doctor_name',
                  'patient_name', 'file_number', 'is_doctor']

clinic/views.py
from django import forms
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, query
from .forms import AppoinmentForm, UserForm, ConsultationForm
from .models import Appoinment, Consultation


# Create your views here.

def create_appoinment(request):
    if not request.user.is_authenticated():
        return render(request, 'clinic/login.html')
    else:
        form = AppoinmentForm(request.POST or None)
        if form.is_valid():
            appoinment = form.save(commit=False)
            appoinment.user = request.user
            appoinment.doctor = request.user
            # if file_type not in IMAGE_FILE_TYPES:
            #     context = {
            #         'appoinment': appoinment,
            #         'form': form,
            #     }
            #     return render(request, 'clinic/create_appoinment.html', context)
            appoinment.save()
            return render(request, 'clinic/detail.html', {'appoinment': appoinment})
        context = {
            'form': form,
        }
        return render(request, 'clinic/create_appoinment.html', context)


def create_consultation(request, appointment_id):
    form = ConsultationForm(request.POST or None)
    appointment = get_object_or_404(Appoinment, pk=appointment_id)
    if form.is_valid():
        appointments_consultation = appointment.consultation_set.all()
        for c in appointments_consultation:
            if c.doctor == form.claned_data.get('doctor'):
                context = {
                    'appointment': appointment,
                    'form': form,
                    'error_message': 'You Have Already Added The Apointment',
                }
                return render(request, 'clinic/create_consultation.html', context)
        consultation = form.save(commit=False)
        consultation.appointment = appointment
        consultation.save()
        return render(request, 'clinic/detail.html', {'appointment': appointment})
    context = {
        'appointment': appointment,
        'form': form,
    }
    return render(request, 'clinic/create_consultation.html', context)


def delete_appointment(request, appointment_id):
    appointment = Appoinment.objects.get(pk=appointment_id)
    appointment.delete()
    appointment = Appoinment.objects.filter(user=request.user)
    return render(request, 'clinic/index.html', {'appointment': appointment})


def delete_consultation(request, appointment_id, consultation_id):
    appointment = get_object_or_404(Appoinment, pk=appointment_id)
    consultation = Consultation.objects.get(pk=consultation_id)
    consultation.delete()
    return render(request, 'clinic/detail.html', {'appointment': appointment})


def detail(request, appointment_id):
    if not request.user.is_authnticated():
        return render(request, 'clinic/login.html')
    else:
        user = request.user
        appointment = get_object_or_404(Appoinment, pk=appointment_id)
        return render(request, 'clinic/detail.html', {'appointment': appointment, 'user': user})


def isdoctor(request, consultation_id):
    consultation = get_object_or_404(Consultation, pk=consultation_id)
    try:
        if consultation.is_doctor:
            consultation.is_doctor == False
        else:
            consultation.is_doctor == True
        consultation.save()
    except (KeyError, Consultation.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


def favourite_appointment(request, appointment_id):
    appointment = get_object_or_404(Appoinment, pk=appointment_id)
    try:
        if appointment.is_doctor:
            appointment.is_doctor == False
        else:
            appointment.is_doctor == True
        appointment.save()
    except (KeyError, Appoinment.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


def index(request):
    if not request.user.is_authenticated():
        return render(request, 'clinic/login.html')
    else:
        appointments = Appoinment.objects.filter(user=request.user)
        consultation_results = Consultation.objects.all()
        query = request.GET.get("q")
        if query:
            appointments = appointments.filter(
                Q(doctor_icontains=query) |
                Q(patient_name_icontains=query)
            ).distinct()
            consultation_results = consultation_results.filter(
                Q(doctor_icontains=query)
            ).distinct()
            return render(request, 'clinic/index.html', {
                'appointments': appointments,
                'consultations': consultation_results,
            })
        else:
            return render(request, 'clinic/index.html', {'appointments': appointments})


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        'form': form
    }
    return render(request, 'clinic/login.html', context)


def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                appoinments = Appoinment.objects.filter(user=request.user)
                return render(request, 'clinic/index.html', context={'appoinments': appoinments})
            else:
                return render(request, 'clinic/login.htl', {'error_message': 'Your Account Has Been Disabled'})
        else:
            return render(request, 'clinic/login.html', {'error_message': 'Invalid LogIn! Please LogIn Again'})
    return render(request, 'clinic/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                appoinments = Appoinment.objects.filter(user=request.user)
                return render(request, 'clinic/index.html', {'appoinments': appoinments})
    context = {
        'form': form,
    }
    return render(request, 'clinic/register.html', context)


def consultations(request, filter_by):
    if not request.user.is_authenticated():
        return render(request, 'clinic/login.html')
    else:
        try:
            consultation_id = []
            for appoinment in Appoinment.objects.filter(user=request.user):
                for consultation in appoinment.consultation_set.all():
                    consultation_id.append(consultation.pk)
            users_consultations = Consultation.objects.filter(
                pk_in=consultation_id)
            if filter_by == 'doctor':
                users_consultations = users_consultations.filter(
                    is_favourite=True)
        except Appoinment.DoesNotExist:
            users_consultations = []
        return render(request, 'clinic/consultations.html', {
            'consultation_list': users_consultations,
            'filter_by': filter_by,
        })

clinic/templates/clinic/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<title>{% block title %}Doctor Clinic{% endblock title %}</title>
	<!-- Bootstrap -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
	<!-- Font Awesome -->
	<script src="https://kit.fontawesome.com/726bcff876.js" crossorigin="anonymous"></script>
	<!-- Custom CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'clinic/style/css' %}">
	<!-- Custom Js -->
	<script type="text/javascript" src="{% static 'clinic/main.js' %}"></script>
</head>
<body>
	<nav class="navbar navbar-inverse">
		<div class="container-fluid">
			<!-- Header -->
			<div class="navbar-header">
				<button class="navbar-toogle" type="button" data-toggle="collapse" data-target="#topNavbar">
					<span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{% url 'clinic:index' %}">Doctor Clinic</a>
			</div>

			<!-- Items -->
			<div class="collapse navbar-collapse" id="topNavbar">
				<ul class="nav navbar-nav">
					<li class="{% block appointments_active %}{% endblock %}"><a href="{% url 'clinic:index' %}"><span><i class="far fa-calendar-check"></i></span> Appointments</a></li>
					<li class="{% block consultations_active %}{% endblock %}"><a href="{% url 'clinic:consultations' 'all' %}"><span><i class="fas fa-phone"></i></span> Consultations</a></li>
				</ul>
				<form class="navbar-form navbar-left" role="search" method="GET" action="{% url 'clinic:index' %}">
                {% csrf_token %}
					<div class="form-group">
						<input class="form-control" type="text" name="q" value="{{ request.GET.q }}"></input>
					</div>
					<button class="btn btn-outline-success">Search</button>
				</form>
				<ul class="nav navbar-nav navbar-right">
					<li>
						<a href="{% url 'clinic:create_appointment' %}">
							<span><i class="fas fa-plus"></i></span> Add Appointment
						</a>
					</li>
					<li>
						<a href="{% url 'clinic:logout_user' %}">
							<span><i class="fas fa-sign-out-alt"></i></span> LogOut
						</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>
    {% block body %}
    
    {% endblock body %}
</body>
</html>

clinic/templates/clinic/base_visitor.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<title>{% block title %}Doctor Clinic{% endblock title %}</title>
	<!-- Bootstrap -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
	<!-- Font Awesome -->
	<script src="https://kit.fontawesome.com/726bcff876.js" crossorigin="anonymous"></script>
	<!-- Custom CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'clinic/style/css' %}">
	<!-- Custom Js -->
	<script type="text/javascript" src="{% static 'clinic/main.js' %}"></script>
</head>
<body>
	<nav class="navbar navbar-inverse">
		<div class="container-fluid">
			<!-- Header -->
			<div class="navbar-header">
				<button class="navbar-toogle" type="button" data-toggle="collapse" data-target="#topNavbar">
					<span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{% url 'clinic:index' %}">Doctor Clinic</a>
			</div>

			<!-- Items -->
            <div class="collapse navbar-collapse" id="topNavbar">
            	<ul class="nav navbar-nav">
            		<li class="{% block register_active %}{% endblock %}"><a href="{% url 'clinic:register' %}"><i class="fas fa-user-plus"></i> Register</a></li>
            		<li class="{% block login_active %}{% endblock  %}"><a href="{% url 'clinic:login_user' %}"><i class="fas fa-sign-in-alt"></i> LogIn</a></li>
            	</ul>
            </div>
        </div>
    </nav>
    {% block body %}
    
    {% endblock body %}
</body>
</html>

clinic/templates/clinic/consultations.html
{% extends 'clinic/base.html' %}
{% block title %}{% endblock title %}
{% block consultations_active %}active{% endblock consultations_active %}

{% block body %}
	<div class="container-fluid consultations-container">
		<div class="row">
			<div class="col-sm-12">
				<ul class="nav nav-pills" style="margin-bottom: 12px;">
					<li role="presentation"{% if filter_by == all %}class="active"{% endif %}><a href="{% url 'clinic:consultations' 'all' %}">View All</a></li>
					<li role="presentation"{% if filter_by == doctor %}class="active"{% endif %}><a href="{% url 'clinic:consultations' 'doctor' %}">Regular Doctor</a></li>
				</ul>
			</div>
		</div>
        <div class="row">
        	<div class="col-sm-12">
        		<div class="panel panel-default">
        			<div class="panel-body">
        				<table class="table">
        					<thead>
        						<tr>
        							<th>Consultation_number</th>
        							<th>Doctor</th>
        							<th>Patient_name</th>
        							<th>File Number</th>
        							<th>Regular Doctor?</th>
        						</tr>
        					</thead>
        					<tbody>
        						{% for consultation in consultation_list %}
                                	<tr>
                                		<td>{{ consultation.consultation_number }}</td>
                                		<td>{{ consultation.doctor }}</td>
                                		<td>{{ consultation.patient_name }}</td>
                                		<td>{{ consultation.is_doctor }}</td>
                                		<td>{{ consultation.appointment.doctor }}</td>
                                		<a href="{% url 'clinic:isdoctor' %}" class="btn-favorite"><span class="{% if consultation.isdoctor %}active{% endif %}"><i class="far fa-heart"></i></span></a>
                                	</tr>
                                {% endfor %}
        					</tbody>
        				</table>
        			</div>
        		</div>
        	</div>
        </div>
	</div>
{% endblock body %}

clinic/templates/clinic/create_consultation.html
{% extends 'clinic/base.html' %}
{% block title %}Add New Consultation{% endblock title %}
{% block appointment_active %}active{% endblock appointment_active %}

{% block body %}
<div class="container-fluid">
	<div class="row">
		<!-- Appointment Info Left -->
		<div class="col-sm-4 col-md-3">
			<div class="panel panel-default">
				<div class="panel-body">
					<a href="{% url 'clinic:detail' appointment.id %}">
						<!-- Clinic Logo Or Hospital Image -->
						<img class="img-responsive" src="#"></img>
					</a>
					<h1>{{ appointment.doctor }} <small>{{ appointment.is_doctor }}</small></h1>
					<h2>{{ appointment.patient_name }}</h2>
				</div>
			</div>
		</div>
		<!-- Consultation Info Right -->
		<div class="col-sm-8 col-md-9">
			<ul class="nav nav-pills" style="margin-bottom: 10px;">
				<li role="presentation"><a href="{% url 'clinic:detail' appointment.id %}">View All</a></li>
				<li role="presentation" class="active"><a href="{% url 'clinic:create_consultation' appointment.id %}">Add New Consultation</a></li>
			</ul>
			<div class="panel panel-default">
				<div class="panel-body">
					<h3>Add New Consultations</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="POST" enctype="multipart/form-data">
                    	{% csrf_token %}
                        <input type="hidden" name="appointment" value="{{ appointment }}">
                        {% include 'clinic/form-template.html' %}
                        <div class="form-group">
                        	<div class="col-sm-offset col-sm-10">
                        		<button type="submit" class="btn btn-outline-success">Submit</button>
                        	</div>
                        </div>
                    </form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock body %}

clinic/templates/clinic/detail.html
{% extends 'clinic/base.html' %}
{% block title %}{{ Appointment }}{% endblock title %}
{% block appointments_active %}active{% endblock appointments_active %}

{% block body %}
	<div class="container-fluid consultations-container">
		<div class="row">
			<!-- Appointment Info Left -->
			<div class="col-sm-4 col-md-3">
				<div class="panel panel-default">
					<div class="panel-body">
						<a href="">
							<!-- Clinic/Hospital Logo/Image -->
							<img src="#">
						</a>
						<h1>{{ appointment.doctor }}<small>{{ appointment.is_doctor }}</small></h1>
						<h2>{{ appointment.patient_name }}</h2>
					</div>
				</div>
			</div>

			<!-- Consultation Info Right -->
			<div class="col-sm-8 col-md-9">
				<ul class="nav nav-pills" style="margin-bottom: 10px;">
					<li role="presentation" class="active"><a href="{% url 'clinic:detail' appointment.id %}">View All</a></li>
					<li role="presentation"><a href="{% url 'clinic:create_consultation' appointment.id %}">Add New Consultations</a></li>
				</ul>
				<div class="panel panel-default">
					<div class="panel-body">
						<h3>All Consultations</h3>
						{% if error_message %}
                        	<p><strong>{{error_message}}</strong></p>
                        {% endif %}

                        <table class="table">
                        	<thead>
                        		<tr>
                        			<th>Time</th>
                        			<th>Date</th>
                        			<th>File Number</th>
                        		</tr>
                        	</thead>
                        	<tbody>
                        		{% for consultation in appointment.consultation_set.all %}
                                    <tr>
                                    	<td>{{ appointment.time }}</td>
                                    	<td>{{ appointment.date }}</td>
                                    	<td>{{ appointment.file_number }}</td>
                                    	<td>
                                    		<a href="{% url 'clinic:isdoctor' consultation.id %}" class="btn-favorite"><span class="{% if consultation.isdoctor %}active{% endif %}"><i class="far fa-heart"></i></span></a>
                                    	</td>
                                        <td>
                                        	<form action="" method="POST" style="display: inline;">
                                                {% csrf_token %}
                                        		<input type="hidden" name="consultation_id" value="{{ consultation.id }}">
                                        		<button type="submit" class="btn btn-outline-danger btn-xs">
                                        			<span><i class="far fa-trash-alt"></i> Delete</span>
                                        		</button>
                                        	</form>
                                        </td>
                                    </tr>
                                {% endfor %}
                        	</tbody>
                        </table>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock body %}

clinic/templates/clinic/form-template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{ field.errors }}</span>
		</div>
		<label class="control-label col-sm-2">{{ field.label_tag }}</label>
		<div class="col-sm-10">{{ field }}</div>
	</div>
{% endfor %}

clinic/templates/clinic/index.html
{% extends 'clinic/base.html' %}
{% block title %}All Appointments{% endblock title %}
{% block appointments_active %}active{% endblock appointments_active %}

{% block body %}
    <div class="appointments-container container-fluid">
    	<!-- Appointments -->
    	<div class="row">
    		<div class="col-sm-12">
    			<h3>Welcome {{user.username}}, Here Are The Appointments For Today.</h3>
    		</div>

    		{% if appointments %}
                {% for appointment in appointments %}
                    <div class="col-sm-4 col-lg-2">
                    	<div class="thumbnail">
                    		<a href="{% url 'clinic:detail' appointment.id %}">
                    			<img src="#">
                    		</a>
                    		<div class="caption">
                    			<h4>{{ appointment.doctor }}</h4>

                    			<!-- View Detail -->
                    			<a href="{% url 'clinic:detail' appointment.id %}" class="btn btn-outline-success btn-sm" role="button">View Details</a>

                    			<!-- Delete Appointment -->
                    			<form action="{% url 'clinic:appointment_delete' appointment.id %}" method="POST" style="display: inline;">

                    				<input type="hidden" name="appointment_id" value="{{ appointment.id }}">
                    				<button type="submit" class="btn btn-outline-danger btn-sm">
                    					<span><i class="far fa-trash-alt"></i> Delete</span>
                    				</button>
                    			</form>
                    		</div>
                    	</div>
                    </div>
                    {% cycle '' '' '' '' '' '<div class="clearfix visibe-lg"></div>' %}
                {% endfor %}
                {% else %}
                	<div class="col-sm-12">
                		<br>
                		<a href="{% url 'clinic:create_appointment' %}">
                			<button type="button" class="btn btn-outline-success">
                				<span><i class="fas fa-plus"></i> Add An Appointment</span>
                			</button>
                		</a>
                	</div>
            {% endif %}
    	</div>

    	<!-- User Searches And There Are Appointment -->
    	{% if consultations %}
            <div class="row">
            	<div class="col-sm-12">
            		<h3>Consultation</h3>
            	</div>
            	<div class="col-sm-12">
            		<div class="panel panel-default">
            			<div class="panel-body">
            				<table class="table">
            					<thead>
            						<tr>
            							<th>Consultation Number</th>
            							<th>Doctor</th>
            							<th>Patient Name</th>
            							<th>File Number</th>
            							<th>Regular Doctor?</th>
            						</tr>
            					</thead>
            					<tbody>
            						{% for consultation in consultations %}
                                        <tr>
                                        	<td>{{ consultation.consultation_number }}</td>
                                        	<td>{{ consultation.appointment.doctor }}</td>
                                        	<td>{{ consultation.patient_name }}</td>
                                        	<td>{{ consultation.file_number }}</td>
                                        	<td>
                                        		<a href="{% url 'clinic:isdoctor' consultation.id %}" class="btn-isdoctor"><span class="{% if consultation.is_doctor %}active{% endif %}"><i class="far fa-heart"></i></span></a>
                                        	</td>
                                        </tr>
                                    {% endfor %}
            					</tbody>
            				</table>
            			</div>
            		</div>
            	</div>
            </div>
        {% endif %}
    </div>
{% endblock body %}

clinic/templates/clinic/login.html
{% extends 'clinic/base.html' %}
{% block title %}LogIn{% endblock title %}
{% block login_active %}active{% endblock login_active %}

{% block body %}
    <div class="container-fluid">
    	<div class="row">
    		<div class="col-sm-12 col-md-6">
    			<div class="panel panel-default">
    				<div class="panel-body">
    					<h3>LogIn</h3>
    					{% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" role="form" action="" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                        	<div class="form-group">
                        		<label class="control-label col-sm-2" for="id_username">
                        			Username : 
                        		</label>
                        		<div class="col-sm-10">
                        			<input type="text" name="username" id="id_username" maxlength="35">
                        		</div>
                        	</div>

                        	<div class="form-group">
                        		<label class="control-label col-sm-2" for="id_password">
                        			Password : 
                        		</label>
                        		<div class="col-sm-10">
                        			<input type="password" name="password" id="id_password" maxlength="35">
                        		</div>
                        	</div>

                        	<div class="form-group">
                        		<div class="col-sm-offset-2 col-sm-10">
                        			<button type="submit" class="btn btn-outline-success">Submit</button>
                        		</div>
                        	</div>
                        </form>
    				</div>
    				<div class="footer">
    					Don't Have An Account? <a href="{% url 'clinic:register' %}">Register</a>
    				</div>
    			</div>
    		</div>
    	</div>
    </div>
{% endblock body %}

clinic/templates/clinic/register.html
{% extends 'clinic/base.html' %}
{% block title %}Register{% endblock title %}
{% block register_active %}active{% endblock register_active %}

{% block body %}
    <div class="container-fluid">
    	<div class="row">
    		<div class="col-sm-12 col-md-6">
    			<div class="panel panel-default">
    				<div class="panel-body">
    					<h3>Register</h3>
    					{% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" role="form" action="" method="POST" enctype="multipart/form-data">
							{% csrf_token %}
							{% include 'clinic/form-template.html' %}
                        	<div class="form-group">
                        		<div class="col-sm-offset-2 col-sm-10">
                        			<button type="submit" class="btn btn-outline-success">Submit</button>
                        		</div>
                        	</div>
                        </form>
    				</div>
    				<div class="panel-footer">
    					Already Have An Account? <a href="{% url 'clinic:login_user' %}">LogIn</a>
    				</div>
    			</div>
    		</div>
    	</div>
    </div>
{% endblock body %}